[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[dependencies]
volatile-register = "0.2.1"

[[bin]]
name = "rust-os"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
