[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile-register = "0.2.1"
# spin = "0.5.2"

[[bin]]
name = "rust-os"
test = false
bench = false

# [dependencies.lazy_static]
# version = "1.4"
# features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
